[package]
name = "srvr"
version = "0.1.0"
description = "Simple HTTP file server"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Tim <me@justim.net>"]
repository = "https://github.com/justim/srvr"
homepage = "https://github.com/justim/srvr"
documentation = "https://github.com/justim/srvr"
rust-version = "1.70"
exclude = ["Dockerfile"]

[dependencies]
anyhow = "1.0.79"
axum = { version = "0.7.4", features = ["http2"] }
axum-extra = { version = "0.9.2", features = ["async-read-body", "typed-header"] }
clap = { version = "4.4.18", features = ["derive"] }
clap_complete = "4.4.9"
httpdate = "1.0.3"
humantime = "2.1.0"
mime = "0.3.17"
mime_guess = "2.0.4"
percent-encoding = "2.3.1"
tokio = { version = "1.35.1", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.1", features = ["fs", "trace", "compression-full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
